# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/usarsim.ui'
#
# Created: Wed Sep 14 21:55:48 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_usar_main_gui(object):
    def setupUi(self, usar_main_gui):
        usar_main_gui.setObjectName(_fromUtf8("usar_main_gui"))
        usar_main_gui.resize(770, 658)
        self.verticalLayout = QtGui.QVBoxLayout(usar_main_gui)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gpbox_connect = QtGui.QGroupBox(usar_main_gui)
        self.gpbox_connect.setFlat(False)
        self.gpbox_connect.setObjectName(_fromUtf8("gpbox_connect"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gpbox_connect)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_ip = QtGui.QLabel(self.gpbox_connect)
        self.label_ip.setObjectName(_fromUtf8("label_ip"))
        self.horizontalLayout.addWidget(self.label_ip)
        self.line_edit_hostip = QtGui.QLineEdit(self.gpbox_connect)
        self.line_edit_hostip.setObjectName(_fromUtf8("line_edit_hostip"))
        self.horizontalLayout.addWidget(self.line_edit_hostip)
        self.label_port = QtGui.QLabel(self.gpbox_connect)
        self.label_port.setObjectName(_fromUtf8("label_port"))
        self.horizontalLayout.addWidget(self.label_port)
        self.line_edit_port = QtGui.QLineEdit(self.gpbox_connect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_port.sizePolicy().hasHeightForWidth())
        self.line_edit_port.setSizePolicy(sizePolicy)
        self.line_edit_port.setObjectName(_fromUtf8("line_edit_port"))
        self.horizontalLayout.addWidget(self.line_edit_port)
        self.btn_connect = QtGui.QPushButton(self.gpbox_connect)
        self.btn_connect.setObjectName(_fromUtf8("btn_connect"))
        self.horizontalLayout.addWidget(self.btn_connect)
        self.btn_disconnect = QtGui.QPushButton(self.gpbox_connect)
        self.btn_disconnect.setObjectName(_fromUtf8("btn_disconnect"))
        self.horizontalLayout.addWidget(self.btn_disconnect)
        self.verticalLayout.addWidget(self.gpbox_connect)
        self.tab_manager = QtGui.QTabWidget(usar_main_gui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_manager.sizePolicy().hasHeightForWidth())
        self.tab_manager.setSizePolicy(sizePolicy)
        self.tab_manager.setTabPosition(QtGui.QTabWidget.North)
        self.tab_manager.setElideMode(QtCore.Qt.ElideNone)
        self.tab_manager.setObjectName(_fromUtf8("tab_manager"))
        self.tab_commands = QtGui.QWidget()
        self.tab_commands.setObjectName(_fromUtf8("tab_commands"))
        self.gridLayout = QtGui.QGridLayout(self.tab_commands)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_2 = QtGui.QFrame(self.tab_commands)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gp_spawn = QtGui.QGroupBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gp_spawn.sizePolicy().hasHeightForWidth())
        self.gp_spawn.setSizePolicy(sizePolicy)
        self.gp_spawn.setObjectName(_fromUtf8("gp_spawn"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gp_spawn)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_4 = QtGui.QFrame(self.gp_spawn)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_spawn = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spawn.sizePolicy().hasHeightForWidth())
        self.label_spawn.setSizePolicy(sizePolicy)
        self.label_spawn.setObjectName(_fromUtf8("label_spawn"))
        self.horizontalLayout_3.addWidget(self.label_spawn)
        self.le_robot_name = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_robot_name.sizePolicy().hasHeightForWidth())
        self.le_robot_name.setSizePolicy(sizePolicy)
        self.le_robot_name.setObjectName(_fromUtf8("le_robot_name"))
        self.horizontalLayout_3.addWidget(self.le_robot_name)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.gp_spawn)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.loc_x = QtGui.QLineEdit(self.frame_3)
        self.loc_x.setObjectName(_fromUtf8("loc_x"))
        self.horizontalLayout_2.addWidget(self.loc_x)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.loc_y = QtGui.QLineEdit(self.frame_3)
        self.loc_y.setObjectName(_fromUtf8("loc_y"))
        self.horizontalLayout_2.addWidget(self.loc_y)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.loc_z = QtGui.QLineEdit(self.frame_3)
        self.loc_z.setObjectName(_fromUtf8("loc_z"))
        self.horizontalLayout_2.addWidget(self.loc_z)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout_2.addWidget(self.gp_spawn, 0, 0, 2, 3)
        self.btn_spawn = QtGui.QPushButton(self.frame_2)
        self.btn_spawn.setObjectName(_fromUtf8("btn_spawn"))
        self.gridLayout_2.addWidget(self.btn_spawn, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 3)
        self.frame = QtGui.QFrame(self.tab_commands)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line_edit_command = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_command.sizePolicy().hasHeightForWidth())
        self.line_edit_command.setSizePolicy(sizePolicy)
        self.line_edit_command.setObjectName(_fromUtf8("line_edit_command"))
        self.horizontalLayout_4.addWidget(self.line_edit_command)
        self.btn_send_command = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_command.sizePolicy().hasHeightForWidth())
        self.btn_send_command.setSizePolicy(sizePolicy)
        self.btn_send_command.setObjectName(_fromUtf8("btn_send_command"))
        self.horizontalLayout_4.addWidget(self.btn_send_command)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.tab_manager.addTab(self.tab_commands, _fromUtf8(""))
        self.tab_control_arms = QtGui.QWidget()
        self.tab_control_arms.setObjectName(_fromUtf8("tab_control_arms"))
        self.tab_manager.addTab(self.tab_control_arms, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_manager)
        self.frame_status = QtGui.QFrame(usar_main_gui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_status.sizePolicy().hasHeightForWidth())
        self.frame_status.setSizePolicy(sizePolicy)
        self.frame_status.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_status.setObjectName(_fromUtf8("frame_status"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_status)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_status = QtGui.QLabel(self.frame_status)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setTextFormat(QtCore.Qt.AutoText)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.verticalLayout_2.addWidget(self.label_status)
        self.text_status = QtGui.QTextEdit(self.frame_status)
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.verticalLayout_2.addWidget(self.text_status)
        self.verticalLayout.addWidget(self.frame_status)

        self.retranslateUi(usar_main_gui)
        self.tab_manager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(usar_main_gui)

    def retranslateUi(self, usar_main_gui):
        usar_main_gui.setWindowTitle(QtGui.QApplication.translate("usar_main_gui", "USARSIM Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.gpbox_connect.setTitle(QtGui.QApplication.translate("usar_main_gui", "Connection Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip.setText(QtGui.QApplication.translate("usar_main_gui", "Host IP", None, QtGui.QApplication.UnicodeUTF8))
        self.line_edit_hostip.setText(QtGui.QApplication.translate("usar_main_gui", "10.50.218.106", None, QtGui.QApplication.UnicodeUTF8))
        self.label_port.setText(QtGui.QApplication.translate("usar_main_gui", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.line_edit_port.setText(QtGui.QApplication.translate("usar_main_gui", "3000", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_connect.setText(QtGui.QApplication.translate("usar_main_gui", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_disconnect.setText(QtGui.QApplication.translate("usar_main_gui", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.gp_spawn.setTitle(QtGui.QApplication.translate("usar_main_gui", "Spawn a Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_spawn.setText(QtGui.QApplication.translate("usar_main_gui", "Robot Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("usar_main_gui", "Robot Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("usar_main_gui", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("usar_main_gui", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("usar_main_gui", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_spawn.setText(QtGui.QApplication.translate("usar_main_gui", "SPAWN", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("usar_main_gui", "Send Direct Commads", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send_command.setText(QtGui.QApplication.translate("usar_main_gui", "SEND", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_manager.setTabText(self.tab_manager.indexOf(self.tab_commands), QtGui.QApplication.translate("usar_main_gui", "Basic Control", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_manager.setTabText(self.tab_manager.indexOf(self.tab_control_arms), QtGui.QApplication.translate("usar_main_gui", "Arm Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("usar_main_gui", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.text_status.setHtml(QtGui.QApplication.translate("usar_main_gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">---</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    usar_main_gui = QtGui.QWidget()
    ui = Ui_usar_main_gui()
    ui.setupUi(usar_main_gui)
    usar_main_gui.show()
    sys.exit(app.exec_())

